// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/google/uuid"
)

type Home struct {
	ID            uuid.UUID `json:"id"`
	OwnerID       uuid.UUID `json:"owner_id"`
	Title         string    `json:"title"`
	FeaturedImage string    `json:"featured_image"`
	Bedrooms      int32     `json:"bedrooms"`
	Bathrooms     int32     `json:"bathrooms"`
	TypeRent      string    `json:"type_rent"`
	Price         int64     `json:"price"`
	ProvinceID    int32     `json:"province_id"`
	CityID        int32     `json:"city_id"`
	Description   string    `json:"description"`
	Amenities     string    `json:"amenities"`
	Area          int32     `json:"area"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Image struct {
	ID        uuid.UUID `json:"id"`
	HouseID   uuid.UUID `json:"house_id"`
	Url       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
}

type Transaction struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	OwnerID       uuid.UUID `json:"owner_id"`
	HouseID       uuid.UUID `json:"house_id"`
	PaymentStatus string    `json:"payment_status"`
	PaymentProof  string    `json:"payment_proof"`
	TotalPayment  int64     `json:"total_payment"`
	CheckIn       time.Time `json:"check_in"`
	CheckOut      time.Time `json:"check_out"`
	TimeRent      string    `json:"time_rent"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID `json:"id"`
	Fullname    string    `json:"fullname"`
	Username    string    `json:"username"`
	Email       string    `json:"email"`
	Role        string    `json:"role"`
	Gender      string    `json:"gender"`
	PhoneNumber string    `json:"phone_number"`
	Password    string    `json:"password"`
	Address     string    `json:"address"`
	Avatar      string    `json:"avatar"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
